return {{ID=5,Info="Temporarily unable to provide service",},
{ID=11,Info="Wrong message",},
{ID=12,Info="Wrong message body",},
{ID=13,Info="bad Request",},
{ID=51,Info="Temporarily unable to provide service",},
{ID=52,Info="Wrong message",},
{ID=53,Info="Wrong message body",},
{ID=54,Info="bad Request ",},
{ID=55,Info="Feature is not turned on",},
{ID=56,Info="The current function is busy, please try again later",},
{ID=101,Info="Account does not exist",},
{ID=102,Info="Account password is wrong",},
{ID=103,Info="Account has been permanently frozen",},
{ID=104,Info="Account has been temporarily frozen",},
{ID=105,Info="Channel does not support this operation",},
{ID=106,Info="The role name is illegal",},
{ID=107,Info="The role name already exists",},
{ID=108,Info="Mobile phone number error",},
{ID=109,Info="Account does not support this operation",},
{ID=110,Info="Client version is too low",},
{ID=111,Info="Need to change password to login",},
{ID=112,Info="Unsupported password",},
{ID=113,Info="Does not support registration operation",},
{ID=114,Info="Channel authentication failed",},
{ID=120,Info="The device already has another account",},
{ID=121,Info="Already bound to another account",},
{ID=131,Info="The server is full",},
{ID=134,Info="Offline cannot be reconnected",},
{ID=135,Info="Token error",},
{ID=136,Info="Login time interval is too short",},
{ID=137,Info="Server verification failed",},
{ID=200,Info="Insufficient character level",},
{ID=201,Info="Insufficient role VIP level",},
{ID=210,Info="The role name is in the wrong format (supports 2-14 characters, English or numbers)",},
{ID=211,Info="The role name contains sensitive words",},
{ID=212,Info="Duplicate role name",},
{ID=214,Info="Role has been permanently frozen",},
{ID=215,Info="Role has been temporarily frozen",},
{ID=216,Info="The role does not exist",},
{ID=218,Info="Role has real-name certification",},
{ID=219,Info="Bad ID card format",},
{ID=220,Info="Role name modification cooling",},
{ID=251,Info="Bad task ID",},
{ID=252,Info="Task status does not support this operation",},
{ID=253,Info="Achievement has not been reached",},
{ID=254,Info="任务章节奖励已领取",},
{ID=255,Info="有未完成的任务 无法领取章节奖励",},
{ID=260,Info="Wrong chest opening type",},
{ID=261,Info="Bad Treasure ID",},
{ID=262,Info="Treasure boxes do not support this operation",},
{ID=265,Info="Check-in has been completed",},
{ID=266,Info="The sign-in reward has been received",},
{ID=270,Info="Bad store ID",},
{ID=271,Info="Store is not open yet",},
{ID=272,Info="Refresh reached the limit",},
{ID=273,Info="Store does not support manual refresh",},
{ID=274,Info="Wrong product ID",},
{ID=275,Info="Products are sold out",},
{ID=276,Info="Insufficient goods",},
{ID=277,Info="Product is subject to purchase and cannot be purchased",},
{ID=281,Info="Message does not exist",},
{ID=282,Info="The email attachment has been received",},
{ID=290,Info="Bad card number",},
{ID=291,Info="Card has expired",},
{ID=292,Info="Request is too frequent or locked (failed 5 times for 10 minutes)",},
{ID=293,Info="This type of card has already been used",},
{ID=300,Info="This paid product cannot be purchased",},
{ID=301,Info="Pay BASE error",},
{ID=302,Info="Payment is closed",},
{ID=350,Info="Chat is not turned on",},
{ID=351,Info="Role has been banned",},
{ID=352,Info="Speak too often, please try again later",},
{ID=353,Info="Private chat object is offline",},
{ID=354,Info="Speech contains sensitive words",},
{ID=355,Info="Wrong channel",},
{ID=356,Info="Voice message no longer exists",},
{ID=357,Info="Not on map, unable to chat",},
{ID=358,Info="很抱歉，对方已将您拉至黑名单，您的消息无法送达",},
{ID=359,Info="私聊功能暂未开启",},
{ID=360,Info="对方暂未开启私聊功能",},
{ID=361,Info="你已将对方拉至黑名单",},
{ID=401,Info="Insufficient assets",},
{ID=402,Info="Lack of physical strength",},
{ID=403,Info="Gold inadequate",},
{ID=404,Info="Inadequate exploits",},
{ID=501,Info="Insufficient number of items",},
{ID=502,Info="Wrong item ID",},
{ID=503,Info="Item does not exist",},
{ID=504,Info="Wrong item type",},
{ID=505,Info="Item cannot be used",},
{ID=506,Info="Not finished tutorial yet, can't delete item",},
{ID=510,Info="The backpack is full",},
{ID=511,Info="The backpack is empty",},
{ID=512,Info="Backpack is closed",},
{ID=513,Info="The backpack is not open",},
{ID=514,Info="Wrong backpack",},
{ID=515,Info="Backpack operation error",},
{ID=516,Info="The backpack contains items that cannot be discarded",},
{ID=517,Info="Equipment durability has reached the lower limit and cannot be used",},
{ID=518,Info="Need synthetic drawings",},
{ID=520,Info="Non-equipment items can't be repaired",},
{ID=521,Info="Equipment is not damaged and cannot be repaired",},
{ID=522,Info="Unable to repair perfectly",},
{ID=600,Info="Wrong activity group",},
{ID=601,Info="Wrong activity",},
{ID=602,Info="Event rewards cannot be collected",},
{ID=1001,Info="Wrong map template ID",},
{ID=1002,Info="Bad map ID",},
{ID=1003,Info="Map does not exist",},
{ID=1004,Info="It's too dangerous out there",},
{ID=1010,Info="The character is dead",},
{ID=1011,Info="The character did not die",},
{ID=1012,Info="Wrong object",},
{ID=1013,Info="Object does not exist",},
{ID=1014,Info="distance is too far",},
{ID=1015,Info="The character is in stealth",},
{ID=1016,Info="The character is not in stealth",},
{ID=1017,Info="The character is not in the grass",},
{ID=1018,Info="Character Stealth Debuff",},
{ID=1020,Info="Wrong trigger",},
{ID=1021,Info="Role drain value is not full",},
{ID=1022,Info="Role carcass in the map",},
{ID=1023,Info="Wrong entrance",},
{ID=1030,Info="The role is already in the team",},
{ID=1031,Info="Bad room number",},
{ID=1032,Info="Wrong Token",},
{ID=1033,Info="The character is in a cross-service state",},
{ID=1034,Info="Cross-service room is closed",},
{ID=1040,Info="Target camp does not exist",},
{ID=1041,Info="Target camp is under attack",},
{ID=1042,Info="Target camp battle cooling",},
{ID=1043,Info="Vengeance function cooling",},
{ID=1101,Info="The building does not exist",},
{ID=1102,Info="The building cannot be moved",},
{ID=1103,Info="The building cannot turn",},
{ID=1104,Info="The building cannot be upgraded",},
{ID=1105,Info="The building cannot be demolished",},
{ID=1106,Info="This location cannot be built",},
{ID=1107,Info="The building has been destroyed and cannot be repaired",},
{ID=1108,Info="Unable to produce",},
{ID=1109,Info="Production has stopped",},
{ID=1110,Info="No other items can be placed in this location",},
{ID=1111,Info="The number of such buildings has reached the ceiling",},
{ID=1112,Info="The building does not allow conversion",},
{ID=1113,Info="The building does not allow repairs",},
{ID=1114,Info="Formula does not exist.",},
{ID=1115,Info="Fuel does not exist.",},
{ID=1120,Info="Have already helped.",},
{ID=1121,Info="Reach help limit.",},
{ID=1150,Info="Agency is not activated",},
{ID=1200,Info="Moving",},
{ID=1201,Info="Not allowed to move to the same location",},
{ID=1202,Info="Bad entry ID",},
{ID=1203,Info="This carrier is not available",},
{ID=1204,Info="Entrance is closed",},
{ID=1250,Info="Role talent has been unlocked",},
{ID=1251,Info="Role talent has not been unlocked",},
{ID=1252,Info="Role talent group has not been unlocked",},
{ID=1253,Info="No talent point consumed, no need to reset",},
{ID=1300,Info="The role is already in the team",},
{ID=1301,Info="The role is not in the team",},
{ID=1302,Info="Character is not the captain",},
{ID=1303,Info="The team is full",},
{ID=1304,Info="Character is offline",},
{ID=1305,Info="Team invitation has expired",},
{ID=1306,Info="Unsupported operation",},
{ID=1307,Info="Target player is not in the team",},
{ID=1308,Info="The team no longer exists",},
{ID=1309,Info="Team can no longer join",},
{ID=1310,Info="The team is not open",},
{ID=1311,Info="Non-team map",},
{ID=1312,Info="有玩家未点击准备",},
{ID=1313,Info="当前门票不足，无法进入地图",},
{ID=1350,Info="避难所功能未开放",},
{ID=1351,Info="该避难所不存在",},
{ID=1352,Info="避难所名称格式错误 6-20个字符 只能汉字英文数字",},
{ID=1353,Info="避难所描述格式错误 少于150个字符 只能汉字英文数字",},
{ID=1354,Info="避难所字含敏感词",},
{ID=1355,Info="避难所描述含敏感词",},
{ID=1356,Info="避难所重名",},
{ID=1360,Info="避难所成员达到上限",},
{ID=1361,Info="加入避难所在CD中",},
{ID=1362,Info="申请已存在 请不要重复申请 ",},
{ID=1364,Info="你已经加入了其他避难所",},
{ID=1365,Info="没有权限",},
{ID=1366,Info="副会长人数达到上限",},
{ID=1367,Info="避难所员不存在",},
{ID=1368,Info="避难所等级太低 ",},
{ID=1369,Info="避难所建筑ID错误 ",},
{ID=1370,Info="贡献值不足",},
{ID=1371,Info="建筑未解锁",},
{ID=1372,Info="今日buff兑换达到上限",},
{ID=1373,Info="捐献次数达到上限",},
{ID=1374,Info="避难所请求捐赠CD中",},
{ID=1375,Info="该玩家已退出避难所，无法捐赠",},
{ID=1376,Info="该请求捐赠已经被其他人完成 ",},
{ID=1377,Info="已经捐赠过",},
{ID=1378,Info="不能捐献",},
{ID=1379,Info="友善度等级不够，不能捐赠",},
{ID=1380,Info="避难所搜索CD中",},
{ID=1381,Info="公告编辑时间处于冷却中，请稍后再来",},
{ID=1382,Info="避难所内电力已用尽，无法继续生产",},
{ID=1383,Info="避难所已经停止运转",},
{ID=1401,Info="Do not allow transactions",},
{ID=1402,Info="Not allowed to leave",},
{ID=1403,Info="Not allowed to remove",},
{ID=1404,Info="Props are not durable enough to allow shelves",},
{ID=1405,Info="Bad parameter type",},
{ID=1406,Info="The number of transactions has reached the limit",},
{ID=1407,Info="The transaction price changes, please repurchase",},
{ID=1408,Info="Trading item does not exist",},
{ID=1409,Info="Insufficient number of transaction items",},
{ID=1410,Info="Requires camp to build express hut",},
{ID=1451,Info="The dialogue does not exist",},
{ID=1500,Info="Friends feature is not turned on",},
{ID=1501,Info="Can't add myself as a friend",},
{ID=1502,Info="The number of friends has reached the limit",},
{ID=1503,Info="The player is already a friend",},
{ID=1504,Info="Target player friend feature is not turned on",},
{ID=1505,Info="Please do not apply repeatedly",},
{ID=1506,Info="The target player is not in the friend application list",},
{ID=1507,Info="The target player has reached the maximum number of friends",},
{ID=1508,Info="您的好友数量已达上限",},
{ID=1509,Info="搜索的目标玩家不存在",},
{ID=1510,Info="对方的好友申请列表达到上限",},
{ID=1511,Info="不能把自己加入黑名单",},
{ID=1512,Info="该玩家已经在黑名单中",},
{ID=1513,Info="黑名单数量达到上限",},
{ID=1514,Info="对方已将你拉黑",},
}