return {{GoodsID=1,AppStoreGoodsID="com.heycb.ydh.goods1",AppStoreGoodsUSID="com.rongygame.sow.goods1",MoliGoodsID="1",},
{GoodsID=3,AppStoreGoodsID="com.heycb.ydh.goods3",AppStoreGoodsUSID="com.rongygame.sow.goods2",MoliGoodsID="2",},
{GoodsID=4,AppStoreGoodsID="com.heycb.ydh.goods4",AppStoreGoodsUSID="com.rongygame.sow.goods3",MoliGoodsID="3",},
{GoodsID=5,AppStoreGoodsID="com.heycb.ydh.goods5",AppStoreGoodsUSID="com.rongygame.sow.goods4",MoliGoodsID="4",},
{GoodsID=7,AppStoreGoodsID="com.heycb.ydh.goods7",AppStoreGoodsUSID="com.rongygame.sow.goods5",MoliGoodsID="5",},
{GoodsID=8,AppStoreGoodsID="com.heycb.ydh.goods8",AppStoreGoodsUSID="com.rongygame.sow.goods6",MoliGoodsID="6",},
{GoodsID=9,AppStoreGoodsID="com.heycb.ydh.goods9",AppStoreGoodsUSID="com.rongygame.sow.goods7",MoliGoodsID="7",},
{GoodsID=10,AppStoreGoodsID="com.heycb.ydh.goods10",AppStoreGoodsUSID="com.rongygame.sow.goods8",MoliGoodsID="8",},
{GoodsID=11,AppStoreGoodsID="com.heycb.ydh.goods11",AppStoreGoodsUSID="com.rongygame.sow.goods9",MoliGoodsID="9",},
{GoodsID=12,AppStoreGoodsID="com.heycb.ydh.goods12",AppStoreGoodsUSID="com.rongygame.sow.goods10",MoliGoodsID="10",},
{GoodsID=13,AppStoreGoodsID="com.heycb.ydh.goods13",AppStoreGoodsUSID="com.rongygame.sow.goods11",MoliGoodsID="11",},
{GoodsID=14,AppStoreGoodsID="com.heycb.ydh.goods14",AppStoreGoodsUSID="com.rongygame.sow.goods12",MoliGoodsID="12",},
{GoodsID=15,AppStoreGoodsID="com.heycb.ydh.goods15",AppStoreGoodsUSID="",MoliGoodsID="",},
}